import type { NextPage } from "next";
import Head from "next/head";
import { useState, useEffect } from "react";
import { Payment } from "types/Razorpay";
import moment from "moment";
import Link from "next/link";

interface Props {
	orders: Payment[] | [];
}

const Home: NextPage<Props> = (props) => {
	const { orders } = props;

	return (
		<>
			<Head>
				<title>Payments</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.png" />
			</Head>
			<main className="w-full min-h-screen flex p-8 flex-col gap-2">
				<Link href="/" passHref>
					<span className="pb-5 flex gap-3 cursor-pointer">
						<svg
							xmlns="http://www.w3.org/2000/svg"
							className="h-6 w-6"
							fill="none"
							viewBox="0 0 24 24"
							stroke="currentColor"
						>
							<path
								strokeLinecap="round"
								strokeLinejoin="round"
								strokeWidth={2}
								d="M7 16l-4-4m0 0l4-4m-4 4h18"
							/>
						</svg>
						Go Back
					</span>
				</Link>
				<h1 className="text-4xl font-bold pb-4">All Donations</h1>
				<div className="w-full flex gap-4 flex-wrap">
					{props.orders.length
						? orders.map((order, key) => {
								return (
									<div
										key={key}
										className="flex flex-col w-full max-w-max justify-between px-4 py-3 bg-gray-100 rounded-lg"
									>
										<span className="flex items-center">
											Email : {order.email}
										</span>
										<span className="flex items-center">
											Amount : {order.amount / 100}rs
										</span>
										<span className="flex items-center">
											Fee : {order.fee / 100}rs
										</span>
									</div>
								);
						  })
						: "Loading..."}
				</div>
			</main>
		</>
	);
};

export async function getServerSideProps() {
	const data: { success: boolean; orders: Payment[] } = await (
		await fetch("http://localhost:3000/api/getorders", {
			method: "GET",
			headers: {
				"Content-Type": "application/json",
			},
		})
	).json();

	return { props: { orders: data?.orders || [] } };
}
export default Home;
